name: Upload Artifact Example

on:
  push:
    branches:
      - main

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List project files
        run: ls -la

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-file
          path: index.html
